% This script serves as an example to compare diffusion encoding gradient
% waveforms generated by an analytical method creating symmetric
% waveforms against a convex optimization method generating concomitant
% field corrected asymmetric waveforms
% Settings and targets can be adapted as suited in parameters.m

SAVE = true;	% Set flag to save results to disk

%% Initialize
close all
path = fileparts(which(mfilename));
addpath(genpath(path))

%% Create waveforms
% Design symmetric waveform
sym = symmetricDiffusion(parameters('sym'));

% Design convex waveforms
asym = convexDiffusion(parameters('asym'), 0, sym.n);
coco = convexDiffusion(parameters('coco'), asym.n, sym.n);

%% Calculate and display results
sym = finalResults(sym);
fprintf(['Symmetric:   ' sym.info '\n']);
asym = finalResults(asym);
fprintf(['Asymmetric:  ' asym.info '\n']);
coco = finalResults(coco);
fprintf(['Concomitant: ' coco.info '\n']);

% Create plots
plotGradients(sym, asym, coco);
plotResiduals(sym, asym, coco);

% Save to disk
if SAVE
	saveResults(sym, asym, coco);
end