function girfDecimNum = girfDecimator(Fs, Fpass, Fstop)
%GIRFDECIMATOR Returns a discrete-time filter object.

% MATLAB Code adapted by Alen Mujkanovic 2018
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generalized REMEZ FIR Lowpass filter designed using the FIRGR function.

% All frequency values are in Hz.
if nargin < 3
    Fs = 100000;			% Sampling Frequency
    Fpass = 50000;			% Passband Frequency
    Fstop = 51000;			% Stopband Frequency
end
Dpass = 0.000057501127785;	% Passband Ripple
Dstop = 0.0001;				% Stopband Attenuation
dens  = 20;					% Density Factor

% Calculate the coefficients using the FIRGR function.
b  = firgr('minorder', [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Dpass ...
           Dstop], {dens});

% Return and save filter coefficients
girfDecimNum = b;

return